"""Adicionando informações para login

Revision ID: b571f8dce969
Revises: e6d9c65d5670
Create Date: 2025-11-01 10:29:18.293349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b571f8dce969'
down_revision: Union[str, Sequence[str], None] = 'e6d9c65d5670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('professor', 'admin', 'super_admin', name='userrole', native_enum=False), nullable=False, server_default='professor'))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
